add_library(multimedia_pipeline_test_support STATIC helpers.cxx)
target_link_libraries(multimedia_pipeline_test_support PUBLIC multimedia_test_support)

function(add_pipeline_test target test_name)
	add_test(NAME "pipeline.${test_name}" COMMAND ${target} "${test_name}")
	set_tests_properties("pipeline.${test_name}" PROPERTIES TIMEOUT 50 LABELS "multimedia;pipeline")
endfunction()

function(add_optional_pipeline_test target test_name)
	add_pipeline_test(${target} ${test_name})
	set_tests_properties("pipeline.${test_name}" PROPERTIES SKIP_RETURN_CODE 77)
endfunction()

add_subdirectory(remux)
add_subdirectory(analytics)
add_subdirectory(video)
add_subdirectory(audio)
add_subdirectory(ocr)
add_subdirectory(negative)
add_subdirectory(implementation)
